jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/kang?useUnicode=true&useSSL=false&autoReconnect=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
jdbc.username=kang
jdbc.password=kang
package.model=armadillo.model
package.mapper=armadillo.mapper
package.xml=mybatis