plugins {
    id 'java-library'
}

group 'armardillo_server'
version '1.0-SNAPSHOT'

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    mavenCentral()
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    api project(":dexlib2")
    api project(":dex2c")
    api project(":arsc")
    // https://mvnrepository.com/artifact/log4j/log4j
    api group: 'log4j', name: 'log4j', version: '1.2.17'
    // https://mvnrepository.com/artifact/com.alibaba/fastjson
    api group: 'com.alibaba', name: 'fastjson', version: '1.2.68'
    // https://mvnrepository.com/artifact/org.mybatis/mybatis
    api group: 'org.mybatis', name: 'mybatis', version: '3.5.5'
    // https://mvnrepository.com/artifact/mysql/mysql-connector-java
    api group: 'mysql', name: 'mysql-connector-java', version: '5.1.49'
    // https://mvnrepository.com/artifact/com.qiniu/qiniu-java-sdk
    api group: 'com.qiniu', name: 'qiniu-java-sdk', version: '7.2.29'
    // https://mvnrepository.com/artifact/org.mybatis/mybatis
    api group: 'org.mybatis', name: 'mybatis', version: '3.5.5'
    // https://mvnrepository.com/artifact/redis.clients/jedis
    api group: 'redis.clients', name: 'jedis', version: '3.3.0'
    // https://mvnrepository.com/artifact/kxml2/kxml2
    api group: 'kxml2', name: 'kxml2', version: '2.3.0'
    // https://mvnrepository.com/artifact/xmlpull/xmlpull
    api group: 'xmlpull', name: 'xmlpull', version: '1.1.3.1'
    // https://mvnrepository.com/artifact/org.redisson/redisson
    api group: 'org.redisson', name: 'redisson', version: '3.14.1'
    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    api group: 'com.google.code.gson', name: 'gson', version: '2.8.6'
    // https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
    api group: 'com.squareup.okhttp3', name: 'okhttp', version: '4.9.3'

}
